# Generated by Django 5.1.2 on 2024-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'regis_table',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.CharField(max_length=600),
        ),
    ]
